config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "search" => "users#search"
  end
  get "search" => "searches#search"
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @past_week_books = {}
    6.downto(0) do |n|
      date = n.days.ago.to_date
      count = @user.books.where(created_at: date.all_day).count
      @past_week_books[date] = count
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_chart.html.erb
<div>
  <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [{
          label: '投稿した本の数',
          data: <%= past_week_books.values %>,
          tension: 0.4,
        }]
      },
      options: {
        plugins: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          }
        },
        scales: {
          x: {
            display: true
          },
          y: {
            display: true,
              min: 0,
              max: 10,
              ticks: {
                stepSize: 1,
            }
          }
        }
      }
    });
  });
</script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to user_followings_path(user.id) do %>
	    <%= user.followings.count %>
	    <% end %>
	   </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to user_followers_path(user.id) do %>
	    <%= user.followers.count %>
	    <% end %>
	  </th>
  </tr>
</table>

<div class='row'>
  <% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>
<% if current_user == user %>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<% end %>

</div>

app/views/users/_posts.html.erb
<h2>投稿数の前日比・前週比</h2>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= today_books = user.books.where(created_at: Date.today.all_day).count %></td>
        <td><%= yesterday_books = user.books.where(created_at: Date.yesterday.all_day).count %></td>
        <td>
          <% if yesterday_books != 0 %>
            <%= (today_books.to_f / yesterday_books.to_f * 100).round %>%
          <% else %>
            0%
          <% end %>
        </td>
      </tr>
  </tbody>
</table>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>前週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= thisweek_books = user.books.where(created_at: Date.current.beginning_of_week..Date.current.end_of_week).count %></td>
        <td><%= lastweek_books = user.books.where(created_at: 1.week.ago.beginning_of_week..1.week.ago.end_of_week).count %></td>
        <td>
          <% if lastweek_books != 0 %>
            <%= (thisweek_books.to_f / lastweek_books.to_f * 100).round %>%
          <% else %>
            0%
          <% end %>
        </td>
      </tr>
  </tbody>
</table>

app/views/users/_search.html.erb
<%= form_with url: user_search_path(user), method: :get, local: false do |f| %>
  <%= f.date_field :created_at %>
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>

app/views/users/_search_result.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_weekposts.html.erb
<h2>7日間分の投稿数</h2>
<table class='table table-bordered'>
  <thead>
      <tr>
        <% past_week_books.each do |date, _| %>
        <th>
          <% if (Date.current - date).to_i.zero? %>
            今日
          <% else %>
            <%= "#{(Date.current - date).to_i}日前" %>
          <% end %>
        <% end %>
        </th>
    </thead>
    <tbody>
      <tr>
        <% past_week_books.each do |_, count| %>
        <td><%= count %></td>
        <% end %>
      </tr>
    </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search_result', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <%= render 'posts', user: @user %>
      <%= render 'weekposts', past_week_books: @past_week_books %>
      <%= render 'chart', past_week_books: @past_week_books %>

      <%= render 'search', user: @user %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search_result', search_book: @search_book %>
        <% end %>
      </div>

    </div>
  </div>
</div>