config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "search" => "users#search"
  end
  get "search" => "searches#search"
 end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      @title ="Users search for '#{params[:word]}'"
    else
      @books = Book.looks(params[:search], params[:word])
      @title ="Books search for '#{params[:word]}'"
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <% if user_signed_in? %>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['User'], ['Book']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-light btn-outline-dark" %>
          <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<h2><%= @title %></h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image, size:'50x50' %>
            <% end %>
          </td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
            <% end %>
          </td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>